# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Directory setup
      run: mkdir $GITHUB_WORKSPACE/_build/

    # Runs a single command using the runners shell
    # to learn more about this docker image, visit https://hub.docker.com/r/rgiessmann/jupyterbook/tags
    # or https://hub.docker.com/layers/rgiessmann/jupyterbook/latest/images/sha256-9ae3025b3a08ae8e2bca80460cbc28c015f482fba39235da555ca150e0876b0d?context=explore
    - name: Run docker
      run: docker run --mount type=bind,source=$GITHUB_WORKSPACE/_build,target=/app/_build --mount type=bind,readonly,source=$GITHUB_WORKSPACE/book,target=/app/book --rm rgiessmann/jupyterbook@sha256:9ae3025b3a08ae8e2bca80460cbc28c015f482fba39235da555ca150e0876b0d

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html/
        publish_branch: gh-pages  
        enable_jekyll: false
        allow_empty_commit: true
